### ISSUE TITLE
How to interpret the StackNet program output?

### ISSUE THREAD

**Issue by ajing** [kaz-Anova/StackNet#17]
I wonder whether the output can give some hint about whether I select the right base models.

I saw something like:

```
 Total ranks after target inclusion: 212409
 Gain from before : 152317
 percentage of unique ranks versus elements size: 13.892484314388511%
 Gain of percentage of unique ranks versus elements size: 9.962202794207%
```

What does it mean? Are they for monitoring?

Thanks

**Comment by kaz-Anova** [comment]
This is is shown if you leave `verbose=true` and just shows you how good the compression ratio when building teh histogram in tree-based methods. If any it just shows how fast it will be (relative to other parameters) and it is not very helpful to gauge performance. 

Your best bet is to tune one parameter at a time using cross validation .
