### ISSUE TITLE
No test in src

### ISSUE THREAD

**Issue by ehsanmok** [kaz-Anova/StackNet#2]
What's the reason that no test was included in the source?

**Comment by kaz-Anova** [comment]
Hey. The short answer for not having a 'test' is that I am not a proper developer - I am self-taught. I have done a lot of testing , but within a format that I am comfortable with (not standard testing framework in Java) and I think it is not in a presentable shape to be shared. 

Do you have any specific suggestions of what is the best way to go on with it?

**Comment by ehsanmok** [comment]
Unit tests as much as you can fit and better to a Maven file instead of uploading JARs to your github repo.

**Comment by xyhXYH** [comment]
您好，您的来信已收到，我将及时阅读并回复。谢谢您！
