### ISSUE TITLE
StackNet usage quesiton

### ISSUE THREAD

**Issue by sreepunith** [kaz-Anova/StackNet#23]
If I am using 2 layer StackNet for a regression problem. Can I use a regression algorithm in the second layer ? The documentation says 
_"A train method needs at least a train_file and a params_file. It also needs at least two algorithms, and the and last layer must not contain a regressor unless the metric is auc and the problem is binary"_
Also are the prediction order preserved (rows) ? Or will the outputs be shuffled?

Thanks

**Comment by kaz-Anova** [comment]
I need to change the decocumentation for that  - this was before **regression** was added as a `task` .

 **Yes you can** have a regressor in the last layer if you specify` task=regression`

The initial order of rows is preserved in the predictions.

**Comment by sreepunith** [comment]
Thank you.
