### ISSUE TITLE
How does your treatment of sparse data differ from full data?

### ISSUE THREAD

**Issue by vinkaga** [kaz-Anova/StackNet#29]
Thanks for this example, I just submitted - I am ranked 78 atm :-)

In your code, the sparse data is treated differently from dense/full data. How is that handled? Are you estimating the missing data before fit or the fit is simply ignoring the missing data?

**Comment by kaz-Anova** [comment]
Missing values **are never ignored**. However algorithms threat them differently.

In native StackNet algorithm ( not xgboost, lightgbm etc) **missing values are handled as zeros.** 

xgboost, lightgbm and other algos may treat these differently .
