### ISSUE TITLE
Any suggestion on merging your StackNet result with results from others on Zillow?

### ISSUE THREAD

**Issue by zilingseu** [kaz-Anova/StackNet#35]
Thanks for sharing your code, and it helped me a lot! I wonder how you can determine the very parameters for each models when you merging them. In the example of Zillow, you chose 0.25 for your own model and 0.75 for the other, and I really want to comprehend the method you used for determining the parameters. I will appreciate it if you can teach me about this~  ^_^

**Comment by kaz-Anova** [comment]
I actually used Leader board feedback and this selection may not be optimum . I believe the public scripts are over-fitted and should have less weight, but for the purposes of incentivising people to use StackNet , I gave it a lower weight , aiming for higher LB results. Ideally, you need to base the logic of  merging models based on your own cross validation.

**Comment by zilingseu** [comment]
Got it, and thanks a lot!
