### ISSUE TITLE
using different feature subsets for individual models

### ISSUE THREAD

**Issue by ifserge** [kaz-Anova/StackNet#40]
Is it possible to use different feature subsets for individual models? If yes, how would it can be configured?

**Comment by goldentom42** [comment]
Hi ifserge, Stacknet does not currently support different dataset for individual model.
What you could do is : 
- feed Stacknet with different datasets and different parameter config, 
- get the level 1 output for each of these configurations
- aggregate all level1 outputs in one file (for train and test data)
- run a final Stacknet config with the level 1 aggregate
Hope this helps

**Comment by kaz-Anova** [comment]
Thank you for the assist @goldentom42 

Actually now there is a way to do it through **python**.

You should have a look at the [python generic model ](https://github.com/kaz-Anova/StackNet#install-python-generic-algorithmsnew). 

If look inside `lib/python` , for example `PythonGenericRegressor0.py` in `line 148 `and `line 168` you can add your own pre-processing of data.  You could do a sub-selection or anything you want.

If you choose this method , bear in mind:

1. You are limited to only python algorithms you have available in your system.
2.  Your data is loaded as sparse data. If you want to chance them to numpy you need to do `X.toarray()`
3. you need to apply the same preprocessing in both train and test (e.g. lines 148,168)

Hope that helps.

**Comment by goldentom42** [comment]
@kaz-Anova, My bad I totally forgot about this great feature...
Congrats for your nice LB position in Zillow's competition!
