### ISSUE TITLE
Issue getting data into .libsvm format from R

### ISSUE THREAD

**Issue by DeluxeAnalyst** [kaz-Anova/StackNet#41]
What is the best way to go about getting a dataset into .libsvm format? Trying to work on the zillow dataset on kaggle, and have done the feature manipulation I want to do in R, but now I want to get the datsset into .libsvm format so I can try StackNet out for the first time, but I have no idea how to get the data into this format, and no solution from googling is working either. 

How do I use R, or something else to get the data into the desired format?

Thanks

**Comment by goldentom42** [comment]
Hello @DeluxeAnalyst, I've googled a bit and I found this post that may be of interest [here](https://vatsalbits.wordpress.com/2016/01/13/csv-to-libsvm/)

I'm not an R developer but I think this should do the trick. As a reminder you must have the target data in the first column of the file for the training data.
Good luck.

**Comment by DeluxeAnalyst** [comment]
Thanks for the reply @goldentom42 . I have found this solution too, but it seems that the problem with this package is that it takes forever to write the file. It seems like there are faster ways to do with with some python scripts, so ill take a stab there and try to put together enough of my python knowledge to run them.
