### ISSUE TITLE
How to deal with the 'model' folder and 'model2' file everytime we run

### ISSUE THREAD

**Issue by qq609299174** [kaz-Anova/StackNet#44]
I follow the steps for Zillow sample. Every time when I tuned the parameters it seems file in model folder changed. Do I have to delete the file or just keep them. Does this affect the results?

**Comment by goldentom42** [comment]
Hi, 
model folder keeps the model fitted with the training data for each fold during each run.
Saved models have different ids at each run so keeping them does not affect results.
However you may want to delete these files to save disk space.
Please keep in mind that if you want to use the predict statement command line( i.e. Java -jar stacknet.jar predict ...) you need to have the corresponding fitted models in the model folder.
Hope this helps.

**Comment by qq609299174** [comment]
Thanks for your help! Not going to delete them. I have a large disk size XD
But another problem here... I am trying to use SklearnknnRegressor. And.. why it is so slow.
I stuck at the first round cv for about 15 minutes. I use 16 threads and my CPU utilization was only 30%.

**Comment by goldentom42** [comment]
I don't think I'm able to assist you on this particular issue. 
If you're on windows this may be related to issue #43
It looks like stacknet sometimes hangs on windows though I never encountered the issue but I'm on win8.1 ...

**Comment by qq609299174** [comment]
Okay! Thank you solved the problem!
