### ISSUE TITLE
Train file format?

### ISSUE THREAD

**Issue by vinkaga** [kaz-Anova/StackNet#52]
I see your scripts saving train file with the following python command
```Python
        np.savetxt(train_file, X, delimiter=",", fmt='%.5f')
```
I have a couple of questions
1. Does it accept any CSV format?
2. Is the X_target the first column of this file?
3. Any other things I should be paying attention to when creating input files?

**Comment by kaz-Anova** [comment]
Does it accept any CSV format?

as long as it is comma separated. 

Is the X_target the first column of this file?

Can you point me to that script? I think it should be. 

Any other things I should be paying attention to when creating input files?

Train file needs to have a target column at the left. Test file may or may not have that. If it has , you have to put `test_target=true` in the command line.

**Comment by vinkaga** [comment]
From the script, the target seems to be in the left column. I did get the `test_target` setting 😄 . Thanks.
