### ISSUE TITLE
multi-label problem

### ISSUE THREAD

**Issue by yangshao** [kaz-Anova/StackNet#6]
hi, if i try to solve a multi-label problem, how can i  prepare the data file and parameter file?

**Comment by kaz-Anova** [comment]
What do you mean multilabel? Multiclass,? or having many target columns?

**Comment by kaz-Anova** [comment]
not much content to go through. I will close this for now.

**Comment by ShiyangChen1991** [comment]
Hi kaz-Anova,

I'm having this problem too. What should I do if there's more than 1 target column? I guess I can always train multiple models for the multiple target columns but is there an easier way our?

Thanks!
