### ISSUE TITLE
Explanation of (double)

### ISSUE THREAD

**Issue by regivm** [kaz-Anova/StackNet#73]
This is not an issue but request a clarification. Inside PARAMETERS.MD file there is explanation of parameters for different ML algorithms. For certain parameters, you have added (double). Please explain what this stands for.

**Comment by kaz-Anova** [comment]
double just means `float` in java :) . so it requires a value with decimal points . 
e.g. `max_depth=3` . This is integer . `max_features=0.34` . This is double.
