### ISSUE TITLE
Failed to generate sparse file

### ISSUE THREAD

**Issue by gdragone1** [kaz-Anova/StackNet#74]
Error showed as follows:
![image](https://user-images.githubusercontent.com/47739935/53387436-c8b09d80-39c1-11e9-9c2b-4af41188e7e8.png)

**Comment by AdityaSoni19031997** [comment]
There's probably a bug in your code.

**Comment by gdragone1** [comment]
> There's probably a bug in your code.

Thank you.But I don't know how to fix it.

**Comment by morenoh149** [comment]
share your code

**Comment by goldentom42** [comment]
Hi there,

Please use `if ytarget is not None:` instead of `if target != None:`

The latter does not work for numpy.arrays or pd.DataFrames

**Comment by goldentom42** [comment]
BTW writing to libsvm format can be done using [sklearn dump_svmllight](https://scikit-learn.org/stable/modules/generated/sklearn.datasets.dump_svmlight_file.html)

hope this helps.

**Comment by AdityaSoni19031997** [comment]
When did dump_svmlight came?
Thanks, didn't know about this at all.

**Comment by goldentom42** [comment]
You're welcome. 

I believe it has been there for some time, I would say at least a year but can't tell you for sure.

**Comment by gdragone1** [comment]
Thank you ! It works.
