### ISSUE TITLE
Error: Could not find or load main class –jar

### ISSUE THREAD

**Issue by vkuznet** [kaz-Anova/StackNet#8]
Hi,
I want to try your package, but I can't run it on Linux:

```
java -jar StackNet.jar train sparse=false has_head=false model=model pred_file=pred.csv train_file=train.csv params=stakcnet.txt verbose=true threads=7 metric=logloss stackdata=false seed=1 folds=5
```

it gives immediately the following error:

```
Error: Could not find or load main class –jar
```

It seems some namespace/classpath issue, could you please either provide instruction how to build jar or specify the namespace/classpath.

Thanks,
Valentin.

**Comment by kaz-Anova** [comment]
Did you try to just copy the jar from the main folder? You don't need to build it.

**Comment by vkuznet** [comment]
Yes, I tried all scenarios, e.g.
- copy jar to a directory with data
- copy data to StackNet and run it from there
- use lower case name (stacknet) instead of StackNet

Btw, the java version I have is 
java version "1.7.0_141"
OpenJDK Runtime Environment (rhel-2.6.10.1.el6_9-x86_64 u141-b02)
OpenJDK 64-Bit Server VM (build 24.141-b02, mixed mode)

**Comment by kaz-Anova** [comment]
I think the answer is in this [thread](https://stackoverflow.com/questions/18093928/what-does-could-not-find-or-load-main-class-mean)  and specifically this comment :

> I had this problem when I was trying to run a Class with a 3rd party library. I invoked java like this: java -cp ../third-party-library.jar com.my.package.MyClass; this does not work, instead it is necessary to add the local folder to the class path as well (separated by :, like this: java -cp ../third-party-library.jar:. com.my.package.MyClass, then it should work . 

The local folder to the class path should be STACKNET:stacknetrun:runstacknet.class . or Maybe without the STACKNET in the beginning. Could you try something around this area? I am pretty sure there is nothing wrong with the Jar.

**Comment by vkuznet** [comment]
Hi, yes this trick works, closing the ticket.
