### ISSUE TITLE
What if I want to use xgboost as first layer model?

### ISSUE THREAD

**Issue by extremin** [kaz-Anova/StackNet#9]
If I want to use xgboost as first layer model, what should I do?

**Comment by kaz-Anova** [comment]
Me too :)

I am still trying to integrate that .  You have to w8 for it  or try to add meta predictions with xgboost to your training data as in [here](https://www.kaggle.com/c/two-sigma-connect-rental-listing-inquiries/discussion/30012)  in the **script create_files_v1.py** . On a positive note I am expecting to add this this week - if everything goes as planned. But it will be fairly untested :(

**Comment by extremin** [comment]
Thx! I'm looking forward to seeing this new feature.
Another question:How could I extract the out-of-fold predictions and the test prediction of first layers?Because I want to use them to train a second layer model, like xgb, lgb, keras etc...

**Comment by kaz-Anova** [comment]
Xgboost has been added. I am closing this.
